# Generated by Django 3.0.3 on 2020-05-22 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=264, unique=True)),
                ('last_name', models.CharField(max_length=264, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTwo.Topic')),
            ],
        ),
    ]
